In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [0]:
from google.colab import files

In [0]:
uploaded = files.upload()

Saving amazon_alexa.tsv to amazon_alexa.tsv


In [0]:
dataset = pd.read_csv('amazon_alexa.tsv', delimiter = '\t', quoting = 3)

In [0]:
print(dataset)

      rating       date             variation  \
0          5  31-Jul-18      Charcoal Fabric    
1          5  31-Jul-18      Charcoal Fabric    
2          4  31-Jul-18        Walnut Finish    
3          5  31-Jul-18      Charcoal Fabric    
4          5  31-Jul-18      Charcoal Fabric    
5          5  31-Jul-18  Heather Gray Fabric    
6          3  31-Jul-18     Sandstone Fabric    
7          5  31-Jul-18      Charcoal Fabric    
8          5  30-Jul-18  Heather Gray Fabric    
9          5  30-Jul-18  Heather Gray Fabric    
10         5  30-Jul-18      Charcoal Fabric    
11         5  30-Jul-18      Charcoal Fabric    
12         5  30-Jul-18           Oak Finish    
13         5  30-Jul-18      Charcoal Fabric    
14         5  30-Jul-18           Oak Finish    
15         5  30-Jul-18  Heather Gray Fabric    
16         5  30-Jul-18  Heather Gray Fabric    
17         5  30-Jul-18  Heather Gray Fabric    
18         5  30-Jul-18      Charcoal Fabric    
19         4  30-Jul

In [0]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [0]:
for i in range(0, 1000):
    review = re.sub('[^a-zA-Z]', ' ', dataset.iloc[:,3][i])
    
    review_1 = re.sub('[^a-zA-Z]', ' ', dataset.iloc[:,2][i])
    
    review = review.lower()
    review_1 = review_1.lower()
    review = review.split()
    review_1 = review_1.split()
    r = review + review_1
   # print(r)
    ps = PorterStemmer()
    r = [ps.stem(word) for word in r if not word in set(stopwords.words('english'))]
    r = ' '.join(r)
    #print(r)
    corpus.append(r)
#print(corpus)


In [0]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X = cv.fit_transform(corpus).toarray()
y = dataset.iloc[:1000,4 ].values
print(X)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [0]:
 from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [0]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf')
classifier.fit(X_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [0]:
y_pred = classifier.predict(X_test)

In [0]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)

In [0]:
print(cm)

[[  0   9]
 [  0 191]]


In [0]:
print(X)

[[1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 1 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]


In [0]:
import statsmodels.formula.api as sm
X = np.append(arr = np.ones((1000,1)).astype(int), values = X , axis =1)
X_opt = X[:,[0,1,2,3,4]]
print(X_opt)
classifier_OLS = sm.OLS(endog = y, exog = X_opt).fit()
classifier_OLS.summary()

[[1 1 1 0 0]
 [1 1 1 0 0]
 [1 1 1 0 1]
 ...
 [1 1 1 0 0]
 [1 1 1 0 0]
 [1 1 1 0 0]]


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                      -0.115
Model:                            OLS   Adj. R-squared:                 -0.119
Method:                 Least Squares   F-statistic:                    -34.28
Date:                Thu, 18 Apr 2019   Prob (F-statistic):               1.00
Time:                        09:46:58   Log-Likelihood:                -114.08
No. Observations:                1000   AIC:                             236.2
Df Residuals:                     996   BIC:                             255.8
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       6.176e+11   2.35e+12      0.263      0.793   -3.99e+12    5.23e+12
x1         -3.088e+11   1.17e+12     -0.263      0.793   -2.61e+12       2e+12
x2         -3.088e+11   1.18e+12     -0.263      0.793   -2.61e+12       2e+12
x3             0.0714      0.111      0.642      0.521      -0.147       0.290
x4            -0.0025      0.051     -0.048      0.962      -0.103       0.098
==============================================================================
Omnibus:                      687.892   Durbin-Watson:                   1.712
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             5345.533
Skew:                          -3.338   Prob(JB):                         0.00
Kurtosis:                      12.150   Cond. No.                     9.36e+18
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 3.42e-35. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [0]:
X_opt = X[:,[0,1,3,4]]
classifier_OLS = sm.OLS(endog = y, exog = X_opt).fit()
classifier_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.001
Model:                            OLS   Adj. R-squared:                 -0.002
Method:                 Least Squares   F-statistic:                    0.4657
Date:                Wed, 17 Apr 2019   Prob (F-statistic):              0.706
Time:                        05:35:46   Log-Likelihood:                -58.877
No. Observations:                1000   AIC:                             125.8
Df Residuals:                     996   BIC:                             145.4
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.9277      0.008    113.047      0.000       0.912       0.944
x1             0.0723      0.105      0.687      0.493      -0.134       0.279
x2             0.0723      0.182      0.397      0.691      -0.285       0.429
x3             0.0723      0.082      0.885      0.377      -0.088       0.233
==============================================================================
Omnibus:                      686.898   Durbin-Watson:                   1.903
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             5322.564
Skew:                          -3.333   Prob(JB):                         0.00
Kurtosis:                      12.127   Cond. No.                         22.4
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [0]:
X_opt = X[:,[0,1,4]]
classifier_OLS = sm.OLS(endog = y, exog = X_opt).fit()
classifier_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.001
Model:                            OLS   Adj. R-squared:                 -0.001
Method:                 Least Squares   F-statistic:                    0.6203
Date:                Wed, 17 Apr 2019   Prob (F-statistic):              0.538
Time:                        05:44:46   Log-Likelihood:                -58.956
No. Observations:                1000   AIC:                             123.9
Df Residuals:                     997   BIC:                             138.6
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.9278      0.008    113.228      0.000       0.912       0.944
x1             0.0722      0.105      0.685      0.493      -0.134       0.279
x2             0.0722      0.082      0.883      0.377      -0.088       0.232
==============================================================================
Omnibus:                      687.066   Durbin-Watson:                   1.902
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             5326.437
Skew:                          -3.334   Prob(JB):                         0.00
Kurtosis:                      12.131   Cond. No.                         13.0
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [0]:
X_opt = X[:,[0,4]]
classifier_OLS = sm.OLS(endog = y, exog = X_opt).fit()
classifier_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.001
Model:                            OLS   Adj. R-squared:                 -0.000
Method:                 Least Squares   F-statistic:                    0.7710
Date:                Thu, 18 Apr 2019   Prob (F-statistic):              0.380
Time:                        09:45:16   Log-Likelihood:                -59.191
No. Observations:                1000   AIC:                             122.4
Df Residuals:                     998   BIC:                             132.2
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.9283      0.008    113.656      0.000       0.912       0.944
x1             0.0717      0.082      0.878      0.380      -0.089       0.232
==============================================================================
Omnibus:                      687.565   Durbin-Watson:                   1.902
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             5337.975
Skew:                          -3.337   Prob(JB):                         0.00
Kurtosis:                      12.142   Cond. No.                         10.1
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [0]:
print(X)

[[1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 1 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]


In [0]:
for i in range(0, 1000):
    review = re.sub('[^a-zA-Z]', ' ', dataset['verified_reviews'][i])
    
  #  review_1 = re.sub('[^a-zA-Z]', ' ', dataset.iloc[:,2][i])
    
    review = review.lower()
  #  review_1 = review_1.lower()
    review = review.split()
   # review_1 = review_1.split()
    r = review 
   # print(r)
    ps = PorterStemmer()
    r = [ps.stem(word) for word in r if not word in set(stopwords.words('english'))]
    r = ' '.join(r)
    #print(r)
    corpus.append(r)
#print(corpus)


In [0]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X = cv.fit_transform(corpus).toarray()
y = dataset.iloc[:3000,4 ].values
y.shape

(3000,)

In [0]:
 from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [0]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear')
classifier.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [0]:
y_pred = classifier.predict(X_test)

In [0]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)

In [0]:
print(cm)

[[  2  51]
 [  8 539]]


In [0]:
y_test.shape

(600,)

In [0]:
541/600

0.9016666666666666